/**
 * @author SAIFIDINE Dayar 
 * @version 1.0
 * Test de l'optimisation de la recherche de la meilleure configuration de connexion entre maisons et générateurs dans un réseau électrique à l'aide de l'automatisation.
 * @date Decembre 2025
 * Resultat : L'optimisation permet de réduire le nombre de générateurs utilisés tout en respectant les contraintes de capacité. 
 * Cependant ce n'est pas suffisant. Les surcharges de toutes les réseaux sont réduites à 0. Cependant, la dispersion n'est que occasionnelement diminuée. 
 * La prochaine version devra donc implémenter une solution qui permettra de rapprocher tous les ecarts entre le taux d'utilisation d'un générateur g avec le taux d'utilisation moyen : Disper = Somme(g in Generateurs)[abs(taux(g) - taux_moy)] -------> 0. 
 */
package org.leanGrid;

import java.util.ArrayList;
import java.util.List;

import org.leanGrid.model.util.*;

public class AlgorithmeTest {
        public static void main(String args[]){
                List<Maison> maisons = new ArrayList<>();
                List<Generateur> generateurs = new ArrayList<>();
                List<Connection> connexions = new ArrayList<>();
        /*******Instance donnée dans le cours********** */
                // System.out.println("Instance donnée dans le cours");
                // Generateur G1 = new Generateur("G1", 60);
                // Generateur G2 = new Generateur("G2", 60);
                // Maison M1 = new Maison("M1",Consommation.FORTE);
                // Maison M2 = new Maison("M2", Consommation.FORTE);
                // Maison M3 = new Maison("M3", Consommation.NORMAL);
                // Maison M4 = new Maison("M4", Consommation.BASSE);
                
                        //**Première configuration
                // Connection C1 = new Connection(M1,G1);
                // Connection C2 = new Connection(M3, G1);
                // Connection C3 = new Connection(M2,G2);
                // Connection C4 = new Connection(M4, G2);
                        //**Deuxième configuration
                // Connection C1 = new Connection(M1, G2);
                // Connection C2 = new Connection(M2,G2);
                // Connection C3 = new Connection(M3,G1);
                // Connection C4 = new Connection(M4, G2);
                // generateurs.add(G1);
                // generateurs.add(G2);
                // maisons.add(M1);
                // maisons.add(M2);
                // maisons.add(M3);
                // maisons.add(M4);
                // connexions.add(C1);
                // connexions.add(C2);
                // connexions.add(C3);
                // connexions.add(C4);

         /*****Instance 1********** */
                // System.out.println("Instance 1");
                // Generateur G1 = new Generateur("gen1", 60);
                // Generateur G2 = new Generateur("gen2", 45);
                // Generateur G3 = new Generateur("gen3", 20);
                // Generateur G4 = new Generateur("gen4",42);
                // Generateur G5 = new Generateur("gen5", 35);
                // Generateur G6 = new Generateur("gen6", 90);
                // Maison M1 = new Maison("maison1",Consommation.NORMAL);
                // Maison M2 = new Maison("maison2",Consommation.BASSE);
                // Maison M3 = new Maison("maison3", Consommation.NORMAL);
                // Maison M4 = new Maison("maison4", Consommation.FORTE);
                // Maison M5 = new Maison("maison5", Consommation.FORTE);
                // Maison M6 = new Maison("maison6", Consommation.NORMAL);
                // Maison M7 = new Maison("maison7", Consommation.NORMAL);
                // Maison M8 = new Maison("maison8", Consommation.FORTE);
                // Maison M9 = new Maison("maison9",Consommation.BASSE);
                // Connection C1 = new Connection(M1, G1);
                // Connection C2 = new Connection(M2, G2);
                // Connection C3 = new Connection(M3, G3);
                // Connection C4 = new Connection(M4, G4);
                // Connection C5 = new Connection(M5, G2);
                // Connection C6 = new Connection(M6, G3);
                // Connection C7 = new Connection(M7, G4);
                // Connection C8 = new Connection(M8,G2);
                // Connection C9 = new Connection(M9, G3);
                // maisons.add(M1);
                // maisons.add(M2);
                // maisons.add(M3);
                // maisons.add(M4);
                // maisons.add(M5);
                // maisons.add(M6);
                // maisons.add(M7);
                // maisons.add(M8);
                // maisons.add(M9);
                // generateurs.add(G1);
                // generateurs.add(G2);
                // generateurs.add(G3);
                // generateurs.add(G4);
                // generateurs.add(G5);
                // generateurs.add(G6);
                // connexions.add(C1);
                // connexions.add(C2);
                // connexions.add(C3);
                // connexions.add(C4);
                // connexions.add(C5);
                // connexions.add(C6);
                // connexions.add(C7);
                // connexions.add(C8);
                // connexions.add(C9);

        /*********Instance 2*********** */
                // System.out.println("Instance 2");
                // Generateur G1 = new Generateur("gen1", 60);
                // Generateur G2 = new Generateur("gen2", 45);
                // Generateur G3 = new Generateur("gen3", 20);
                // Generateur G4 = new Generateur("gen4",42);
                // Generateur G5 = new Generateur("gen5", 35);
                // Generateur G6 = new Generateur("gen6", 90);
                // Generateur G7 = new Generateur("gen7", 10);
                // Generateur G8 = new Generateur("gen8", 30);
                // Maison M1 = new Maison("maison1",Consommation.NORMALE);
                // Maison M2 = new Maison("maison2",Consommation.BASSE);
                // Maison M3 = new Maison("maison3", Consommation.NORMALE);
                // Maison M4 = new Maison("maison4", Consommation.FORTE);
                // Maison M5 = new Maison("maison5", Consommation.FORTE);
                // Maison M6 = new Maison("maison6", Consommation.NORMALE);
                // Maison M7 = new Maison("maison7", Consommation.NORMALE);
                // Maison M8 = new Maison("maison8", Consommation.FORTE);
                // Maison M9 = new Maison("maison9",Consommation.BASSE);
                // Connection C1 = new Connection(M1, G1);
                // Connection C2 = new Connection(M2, G2);
                // Connection C3 = new Connection(M3, G3);
                // Connection C4 = new Connection(M4, G4);
                // Connection C5 = new Connection(M5, G2);
                // Connection C6 = new Connection(M6, G3);
                // Connection C7 = new Connection(M7, G4);
                // Connection C8 = new Connection(M8,G2);
                // Connection C9 = new Connection(M9, G3);
                // maisons.add(M1);
                // maisons.add(M2);
                // maisons.add(M3);
                // maisons.add(M4);
                // maisons.add(M5);
                // maisons.add(M6);
                // maisons.add(M7);
                // maisons.add(M8);
                // maisons.add(M9);
                // generateurs.add(G1);
                // generateurs.add(G2);
                // generateurs.add(G3);
                // generateurs.add(G4);
                // generateurs.add(G5);
                // generateurs.add(G6);
                // generateurs.add(G7);
                // generateurs.add(G8);
                // connexions.add(C1);
                // connexions.add(C2);
                // connexions.add(C3);
                // connexions.add(C4);
                // connexions.add(C5);
                // connexions.add(C6);
                // connexions.add(C7);
                // connexions.add(C8);
                // connexions.add(C9);

        /***********Instance 3 ************** */
                // System.out.println("Instance 3");
                // Generateur G1 = new Generateur("gen1", 50);
                // Generateur G2 = new Generateur("gen2", 60);
                // Generateur G3 = new Generateur("gen3", 40);
                // Generateur G4 = new Generateur("gen4",10);
                // Maison M1 = new Maison("maison1",Consommation.NORMALE);
                // Maison M2 = new Maison("maison2",Consommation.NORMALE);
                // Maison M3 = new Maison("maison3", Consommation.BASSE);
                // Maison M4 = new Maison("maison4", Consommation.FORTE);
                // Maison M5 = new Maison("maison5", Consommation.NORMALE);
                // Maison M6 = new Maison("maison6", Consommation.BASSE);
                // Maison M7 = new Maison("maison7", Consommation.BASSE);
                // Maison M8 = new Maison("maison8", Consommation.NORMALE);
                // Maison M9 = new Maison("maison9",Consommation.BASSE);
                // Connection C1 = new Connection(M1, G1);
                // Connection C2 = new Connection(M2, G2);
                // Connection C3 = new Connection(M3, G3);
                // Connection C4 = new Connection(M4, G4);
                // Connection C5 = new Connection(M5, G2);
                // Connection C6 = new Connection(M6, G3);
                // Connection C7 = new Connection(M7, G4);
                // Connection C8 = new Connection(M8,G2);
                // Connection C9 = new Connection(M9, G3);
                // maisons.add(M1);
                // maisons.add(M2);
                // maisons.add(M3);
                // maisons.add(M4);
                // maisons.add(M5);
                // maisons.add(M6);
                // maisons.add(M7);
                // maisons.add(M8);
                // maisons.add(M9);
                // generateurs.add(G1);
                // generateurs.add(G2);
                // generateurs.add(G3);
                // generateurs.add(G4);
                // connexions.add(C1);
                // connexions.add(C2);
                // connexions.add(C3);
                // connexions.add(C4);
                // connexions.add(C5);
                // connexions.add(C6);
                // connexions.add(C7);
                // connexions.add(C8);
                // connexions.add(C9);

        /******Instance 4 *************/ 
                // System.out.println("Instance 4");     
                // Generateur G1 = new Generateur("gen1", 50);
                // Generateur G2 = new Generateur("gen2", 60);
                // Generateur G3 = new Generateur("gen3", 40);
                // Generateur G4 = new Generateur("gen4",10);
                // Generateur G5 = new Generateur("gen5", 20);
                // Generateur G6 = new Generateur("gen6", 40);
                // Maison M1 = new Maison("maison1",Consommation.NORMALE);
                // Maison M2 = new Maison("maison2",Consommation.NORMALE);
                // Maison M3 = new Maison("maison3", Consommation.BASSE);
                // Maison M4 = new Maison("maison4", Consommation.FORTE);
                // Maison M5 = new Maison("maison5", Consommation.NORMALE);
                // Maison M6 = new Maison("maison6", Consommation.BASSE);
                // Maison M7 = new Maison("maison7", Consommation.BASSE);
                // Maison M8 = new Maison("maison8", Consommation.NORMALE);
                // Maison M9 = new Maison("maison9",Consommation.BASSE);
                // Maison M10 = new Maison("maison10", Consommation.FORTE);
                // Maison M11 = new Maison("maison11", Consommation.NORMALE);
                // Connection C1 = new Connection(M1, G1);
                // Connection C2 = new Connection(M2, G2);
                // Connection C3 = new Connection(M3, G3);
                // Connection C4 = new Connection(M4, G4);
                // Connection C5 = new Connection(M5, G2);
                // Connection C6 = new Connection(M6, G3);
                // Connection C7 = new Connection(M7, G4);
                // Connection C8 = new Connection(M8,G2);
                // Connection C9 = new Connection(M9, G3);
                // Connection C10 = new Connection(M10, G2);
                // Connection C11 = new Connection(M11, G3);
                // maisons.add(M1);
                // maisons.add(M2);
                // maisons.add(M3);
                // maisons.add(M4);
                // maisons.add(M5);
                // maisons.add(M6);
                // maisons.add(M7);
                // maisons.add(M8);
                // maisons.add(M9);
                // maisons.add(M10);
                // maisons.add(M11);
                // generateurs.add(G1);
                // generateurs.add(G2);
                // generateurs.add(G3);
                // generateurs.add(G4);
                // generateurs.add(G5);
                // generateurs.add(G6);
                // connexions.add(C1);
                // connexions.add(C2);
                // connexions.add(C3);
                // connexions.add(C4);
                // connexions.add(C5);
                // connexions.add(C6);
                // connexions.add(C7);
                // connexions.add(C8);
                // connexions.add(C9);
                // connexions.add(C10);
                // connexions.add(C11);

        /*******Instance 5********** */
                // System.out.println("Instance 5");
                // Generateur G1 = new Generateur("gen1", 10);
                // Generateur G2 = new Generateur("gen2", 20);
                // Generateur G3 = new Generateur("gen3", 30);
                // Generateur G4 = new Generateur("gen4",40);
                // Generateur G5 = new Generateur("gen5", 50);
                // Generateur G6 = new Generateur("gen6", 60);
                // Generateur G7 = new Generateur("gen7", 70);
                // Generateur G8 = new Generateur("gen8", 80);
                // Maison M1 = new Maison("maison1",Consommation.NORMALE);
                // Maison M2 = new Maison("maison2",Consommation.NORMALE);
                // Maison M3 = new Maison("maison3", Consommation.NORMALE);
                // Maison M4 = new Maison("maison4", Consommation.NORMALE);
                // Maison M5 = new Maison("maison5", Consommation.NORMALE);
                // Maison M6 = new Maison("maison6", Consommation.NORMALE);
                // Maison M7 = new Maison("maison7", Consommation.NORMALE);
                // Maison M8 = new Maison("maison8", Consommation.NORMALE);
                // Maison M9 = new Maison("maison9",Consommation.NORMALE);
                // Connection C1 = new Connection(M1, G1);
                // Connection C2 = new Connection(M2, G2);
                // Connection C3 = new Connection(M3, G3);
                // Connection C4 = new Connection(M4, G4);
                // Connection C5 = new Connection(M5, G2);
                // Connection C6 = new Connection(M6, G3);
                // Connection C7 = new Connection(M7, G4);
                // Connection C8 = new Connection(M8,G2);
                // Connection C9 = new Connection(M9, G3);
                // maisons.add(M1);
                // maisons.add(M2);
                // maisons.add(M3);
                // maisons.add(M4);
                // maisons.add(M5);
                // maisons.add(M6);
                // maisons.add(M7);
                // maisons.add(M8);
                // maisons.add(M9);
                // generateurs.add(G1);
                // generateurs.add(G2);
                // generateurs.add(G3);
                // generateurs.add(G4);
                // generateurs.add(G5);
                // generateurs.add(G6);
                // generateurs.add(G7);
                // generateurs.add(G8);
                // connexions.add(C1);
                // connexions.add(C2);
                // connexions.add(C3);
                // connexions.add(C4);
                // connexions.add(C5);
                // connexions.add(C6);
                // connexions.add(C7);
                // connexions.add(C8);
                // connexions.add(C9);
                
        /******Instance 5 très grande******* */
                // System.out.println("Instance 5 très grande");
                // Generateur G1 = new Generateur("gen1", 70);
                // Generateur G2 = new Generateur("gen2", 35);
                // Generateur G3 = new Generateur("gen3", 40);
                // Generateur G4 = new Generateur("gen4",62);
                // Generateur G5 = new Generateur("gen5", 42);
                // Generateur G6 = new Generateur("gen6", 83);
                // Generateur G7 = new Generateur("gen7", 15);
                // Generateur G8 = new Generateur("gen8", 50);
                // Generateur G9 = new Generateur("gen9", 50);
                // Maison M1 = new Maison("maison1",Consommation.NORMALE);
                // Maison M2 = new Maison("maison2",Consommation.BASSE);
                // Maison M3 = new Maison("maison3", Consommation.NORMALE);
                // Maison M4 = new Maison("maison4", Consommation.FORTE);
                // Maison M5 = new Maison("maison5", Consommation.FORTE);
                // Maison M6 = new Maison("maison6", Consommation.NORMALE);
                // Maison M7 = new Maison("maison7", Consommation.NORMALE);
                // Maison M8 = new Maison("maison8", Consommation.FORTE);
                // Maison M9 = new Maison("maison9",Consommation.BASSE);
                // Maison M10 = new Maison("maison10", Consommation.NORMALE);
                // Maison M11 = new Maison("maison11", Consommation.BASSE);
                // Maison M12 = new Maison("maison12", Consommation.NORMALE);
                // Maison M13 = new Maison("maison13", Consommation.FORTE);
                // Maison M14 = new Maison("maison14", Consommation.FORTE);
                // Maison M15 = new Maison("maison15", Consommation.NORMALE);
                // Maison M16 = new Maison("maison16", Consommation.NORMALE);
                // Maison M17 = new Maison("maison17", Consommation.FORTE);
                // Maison M18 = new Maison("maison18", Consommation.BASSE);
                // Connection C1 = new Connection(M1, G1);
                // Connection C2 = new Connection(M2, G2);
                // Connection C3 = new Connection(M3, G3);
                // Connection C4 = new Connection(M4, G4);
                // Connection C5 = new Connection(M5, G2);
                // Connection C6 = new Connection(M6, G3);
                // Connection C7 = new Connection(M7, G4);
                // Connection C8 = new Connection(M8,G2);
                // Connection C9 = new Connection(M9, G3);
                // Connection C10 = new Connection(M10, G1);
                // Connection C11 = new Connection(M11, G2);
                // Connection C12 = new Connection(M12, G3);
                // Connection C13 = new Connection(M13, G4);
                // Connection C14 = new Connection(M14, G2);
                // Connection C15 = new Connection(M15, G3);
                // Connection C16 = new Connection(M16, G4);
                // Connection C17 = new Connection(M17, G2);
                // Connection C18 = new Connection(M18, G3);
                // maisons.add(M1); 
                // maisons.add(M2);
                // maisons.add(M3);
                // maisons.add(M4);
                // maisons.add(M5);
                // maisons.add(M6);
                // maisons.add(M7);
                // maisons.add(M8);
                // maisons.add(M9);
                // maisons.add(M10);
                // maisons.add(M11);
                // maisons.add(M12);
                // maisons.add(M13);
                // maisons.add(M14);
                // maisons.add(M15);
                // maisons.add(M16);
                // maisons.add(M17);
                // maisons.add(M18);
                // generateurs.add(G1);
                // generateurs.add(G2);
                // generateurs.add(G3);
                // generateurs.add(G4);
                // generateurs.add(G5);
                // generateurs.add(G6);
                // generateurs.add(G7);
                // generateurs.add(G8);
                // generateurs.add(G9);
                // connexions.add(C1);
                // connexions.add(C2);
                // connexions.add(C3);
                // connexions.add(C4);
                // connexions.add(C5);
                // connexions.add(C6);
                // connexions.add(C7);
                // connexions.add(C8);
                // connexions.add(C9);
                // connexions.add(C10);
                // connexions.add(C11);
                // connexions.add(C12);
                // connexions.add(C13);
                // connexions.add(C14);
                // connexions.add(C15);
                // connexions.add(C16);
                // connexions.add(C17);
                // connexions.add(C18); 
        /********Instance 6************** */
                // System.out.println("Instance 6");
                // Generateur G1 = new Generateur("gen1", 10);
                // Generateur G2 = new Generateur("gen2", 20);
                // Generateur G3 = new Generateur("gen3", 30);
                // Generateur G4 = new Generateur("gen4",40);
                // Generateur G5 = new Generateur("gen5", 50);
                // Generateur G6 = new Generateur("gen6", 60);
                // Generateur G7 = new Generateur("gen7", 70);
                // Generateur G8 = new Generateur("gen8", 80);
                // Maison M1 = new Maison("maison1",Consommation.BASSE);
                // Maison M2 = new Maison("maison2",Consommation.BASSE);
                // Maison M3 = new Maison("maison3", Consommation.BASSE);
                // Maison M4 = new Maison("maison4", Consommation.BASSE);
                // Maison M5 = new Maison("maison5", Consommation.BASSE);
                // Maison M6 = new Maison("maison6", Consommation.BASSE);
                // Maison M7 = new Maison("maison7", Consommation.BASSE);
                // Maison M8 = new Maison("maison8", Consommation.BASSE);
                // Maison M9 = new Maison("maison9",Consommation.BASSE);
                // Connection C1 = new Connection(M1, G1);
                // Connection C2 = new Connection(M2, G2);
                // Connection C3 = new Connection(M3, G3);
                // Connection C4 = new Connection(M4, G4);
                // Connection C5 = new Connection(M5, G2);
                // Connection C6 = new Connection(M6, G3);
                // Connection C7 = new Connection(M7, G4);
                // Connection C8 = new Connection(M8,G2);
                // Connection C9 = new Connection(M9, G3);
                // maisons.add(M1);
                // maisons.add(M2);
                // maisons.add(M3);
                // maisons.add(M4);
                // maisons.add(M5);
                // maisons.add(M6);
                // maisons.add(M7);
                // maisons.add(M8);
                // maisons.add(M9);
                // generateurs.add(G1);
                // generateurs.add(G2);
                // generateurs.add(G3);
                // generateurs.add(G4);
                // generateurs.add(G5);
                // generateurs.add(G6);
                // generateurs.add(G7);
                // generateurs.add(G8);
                // connexions.add(C1);
                // connexions.add(C2);
                // connexions.add(C3);
                // connexions.add(C4);
                // connexions.add(C5);
                // connexions.add(C6);
                // connexions.add(C7);
                // connexions.add(C8);
                // connexions.add(C9);

        /*******Instance 6 très grande ******* */
                // System.out.println("Instance 6 très grande");
                // Generateur G1 = new Generateur("gen1", 70);
                // Generateur G2 = new Generateur("gen2", 350);
                // Generateur G3 = new Generateur("gen3", 460);
                // Generateur G4 = new Generateur("gen4",162);
                // Generateur G5 = new Generateur("gen5", 278);
                // Generateur G6 = new Generateur("gen6", 33);
                // Generateur G7 = new Generateur("gen7", 223);
                
                // Maison M1 = new Maison("maison1",Consommation.NORMALE);
                // Maison M2 = new Maison("maison2",Consommation.BASSE);
                // Maison M3 = new Maison("maison3", Consommation.NORMALE);
                // Maison M4 = new Maison("maison4", Consommation.FORTE);
                // Maison M5 = new Maison("maison5", Consommation.FORTE);
                // Maison M6 = new Maison("maison6", Consommation.NORMALE);
                // Maison M7 = new Maison("maison7", Consommation.NORMALE);
                // Maison M8 = new Maison("maison8", Consommation.FORTE);
                // Maison M9 = new Maison("maison9",Consommation.BASSE);
                // Maison M10 = new Maison("maison10", Consommation.NORMALE);
                // Maison M11 = new Maison("maison11", Consommation.BASSE);
                // Maison M12 = new Maison("maison12", Consommation.NORMALE);
                // Maison M13 = new Maison("maison13", Consommation.FORTE);
                // Maison M14 = new Maison("maison14", Consommation.FORTE);
                // Maison M15 = new Maison("maison15", Consommation.NORMALE);
                // Maison M16 = new Maison("maison16", Consommation.NORMALE);
                // Maison M17 = new Maison("maison17", Consommation.FORTE);
                // Maison M18 = new Maison("maison18", Consommation.BASSE);
                // Connection C1 = new Connection(M1, G1);
                // Connection C2 = new Connection(M2, G2);
                // Connection C3 = new Connection(M3, G3);
                // Connection C4 = new Connection(M4, G4);
                // Connection C5 = new Connection(M5, G2);
                // Connection C6 = new Connection(M6, G3);
                // Connection C7 = new Connection(M7, G4);
                // Connection C8 = new Connection(M8,G2);
                // Connection C9 = new Connection(M9, G3);
                // Connection C10 = new Connection(M10, G1);
                // Connection C11 = new Connection(M11, G2);
                // Connection C12 = new Connection(M12, G3);
                // Connection C13 = new Connection(M13, G4);
                // Connection C14 = new Connection(M14, G2);
                // Connection C15 = new Connection(M15, G3);
                // Connection C16 = new Connection(M16, G4);
                // Connection C17 = new Connection(M17, G2);
                // Connection C18 = new Connection(M18, G3);
                // maisons.add(M1); 
                // maisons.add(M2);
                // maisons.add(M3);
                // maisons.add(M4);
                // maisons.add(M5);
                // maisons.add(M6);
                // maisons.add(M7);
                // maisons.add(M8);
                // maisons.add(M9);
                // maisons.add(M10);
                // maisons.add(M11);
                // maisons.add(M12);
                // maisons.add(M13);
                // maisons.add(M14);
                // maisons.add(M15);
                // maisons.add(M16);
                // maisons.add(M17);
                // maisons.add(M18);
                // generateurs.add(G1);
                // generateurs.add(G2);
                // generateurs.add(G3);
                // generateurs.add(G4);
                // generateurs.add(G5);
                // generateurs.add(G6);
                // generateurs.add(G7);
                // connexions.add(C1);
                // connexions.add(C2);
                // connexions.add(C3);
                // connexions.add(C4);
                // connexions.add(C5);
                // connexions.add(C6);
                // connexions.add(C7);
                // connexions.add(C8);
                // connexions.add(C9);
                // connexions.add(C10);
                // connexions.add(C11);
                // connexions.add(C12);
                // connexions.add(C13);
                // connexions.add(C14);
                // connexions.add(C15);
                // connexions.add(C16);
                // connexions.add(C17);
                // connexions.add(C18);
        /*******Instance 7*************** */
                // System.out.println("Instance 7");
                // Generateur G1 = new Generateur("gen1", 10);
                // Generateur G2 = new Generateur("gen2", 20);
                // Generateur G3 = new Generateur("gen3", 30);
                // Generateur G4 = new Generateur("gen4",40);
                // Generateur G5 = new Generateur("gen5", 50);
                // Generateur G6 = new Generateur("gen6", 60);
                // Generateur G7 = new Generateur("gen7", 70);
                // Generateur G8 = new Generateur("gen8", 80);
                // Generateur G9 = new Generateur("gen9", 90);
                // Maison M1 = new Maison("maison1",Consommation.FORTE);
                // Maison M2 = new Maison("maison2",Consommation.FORTE);
                // Maison M3 = new Maison("maison3", Consommation.FORTE);
                // Maison M4 = new Maison("maison4", Consommation.FORTE);
                // Maison M5 = new Maison("maison5", Consommation.FORTE);
                // Maison M6 = new Maison("maison6", Consommation.FORTE);
                // Maison M7 = new Maison("maison7", Consommation.FORTE);
                // Maison M8 = new Maison("maison8", Consommation.FORTE);
                // Maison M9 = new Maison("maison9",Consommation.FORTE);
                // Connection C1 = new Connection(M1, G1);
                // Connection C2 = new Connection(M2, G2);
                // Connection C3 = new Connection(M3, G3);
                // Connection C4 = new Connection(M4, G4);
                // Connection C5 = new Connection(M5, G2);
                // Connection C6 = new Connection(M6, G3);
                // Connection C7 = new Connection(M7, G4);
                // Connection C8 = new Connection(M8,G2);
                // Connection C9 = new Connection(M9, G3);
                // maisons.add(M1); 
                // maisons.add(M2);
                // maisons.add(M3);
                // maisons.add(M4);
                // maisons.add(M5);
                // maisons.add(M6);
                // maisons.add(M7);
                // maisons.add(M8);
                // maisons.add(M9);
                // generateurs.add(G1);
                // generateurs.add(G2);
                // generateurs.add(G3);
                // generateurs.add(G4);
                // generateurs.add(G5);
                // generateurs.add(G6);
                // generateurs.add(G7);
                // generateurs.add(G8);
                // generateurs.add(G9);
                // connexions.add(C1);
                // connexions.add(C2);
                // connexions.add(C3);
                // connexions.add(C4);
                // connexions.add(C5);
                // connexions.add(C6);
                // connexions.add(C7);
                // connexions.add(C8);
                // connexions.add(C9);
        



                /****Test avant l'optimisation*** */
                System.out.println("Avant optimisation :");
                Reseau r_test = new Reseau(generateurs, maisons, connexions);
                System.out.println(r_test);
                System.out.println("Après optimisation:");
                Algorithme a1 = new Algorithme(r_test, 10);
                Reseau solution1= a1.launch();
                
                System.out.println(solution1);

              

        }
    

}
